name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image
      run: | 
        export BRANCH_NAME=`echo $GITHUB_REF | sed "s/refs\/heads\///"`
        export CACHE_IMAGE=diverofdark/anonymousfzbot:`echo $BRANCH_NAME | tr '/' '_'  | tr '@' '_'`
        echo "BRANCH_NAME: $BRANCH_NAME"
        echo "GITHUB_SHA: $GITHUB_SHA"
        docker build --build-arg "CiCommitName=$BRANCH_NAME" --build-arg "CiCommitHash=$GITHUB_SHA" --build-arg IsProduction=true -t $CACHE_IMAGE .

    - name: Push the Docker image
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      env: 
        DOCKER_LOGIN: ${{ secrets.DOCKER_LOGIN }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        export BRANCH_NAME=`echo $GITHUB_REF | sed "s/refs\/heads\///"`
        export CACHE_IMAGE=diverofdark/anonymousfzbot:`echo $BRANCH_NAME | tr '/' '_'  | tr '@' '_'`
        docker login --username="$DOCKER_LOGIN" --password="$DOCKER_PASSWORD"
        docker push $CACHE_IMAGE
